import {chromium} from './browser.mjs';
import {readFileSync,writeFileSync,copyFileSync,mkdirSync} from 'node:fs';
const root='art/ui-screens/v02',manifest=JSON.parse(readFileSync(root+'/manifest.json','utf8'));
manifest.screens=manifest.screens.filter(s=>!s.extra);
const b=await chromium.launch({headless:true});try{
const p=await b.newPage({viewport:{width:360,height:780},deviceScaleFactor:3});
for(const [id,label]of [['home','게임 홈 · 전체'],['inventory','인벤토리 · 전체'],['puzzle-circuit','회로도 퍼즐 · 전체'],['notebook','수첩 · 전체'],['settings','설정 · 전체']]){
 await p.setViewportSize({width:360,height:780});await p.goto('http://127.0.0.1:5173/ui-preview.html?screen='+id+'&focus=1');await p.locator('.game-shell').waitFor();
 await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});
 const selector=id==='home'?'.home-scroll':'.sheet-scroll';let height=780;
 for(let n=0;n<2;n++){height+=await p.locator(selector).evaluate(el=>Math.ceil(el.scrollHeight-el.clientHeight+4));await p.setViewportSize({width:360,height});}
 await p.evaluate(()=>document.activeElement?.blur());const file=String(manifest.screens.length+3).padStart(2,'0')+'_'+id+'_full_v02.png';
 await p.screenshot({path:root+'/'+file});manifest.screens.push({id:id+'-full',label,description:'스크롤 내용을 모두 펼친 긴 화면',file,width:1080,height:height*3,extra:true});console.log(file,height*3);
}
}finally{await b.close();}
manifest.screens.splice(19,0,{id:'title-refresh',label:'타이틀 · 이전 구도 수정',description:'앞서 제공한 이미지에 프리텐다드 적용',file:'20_title_390x844_pretendard_v02.png',width:390,height:844,extra:true},{id:'explore-chair-refresh',label:'의자 앞 탐색 · 이전 구도 수정',description:'앞서 제공한 이미지에 프리텐다드 적용',file:'21_explore-chair_390x844_pretendard_v02.png',width:390,height:844,extra:true});
mkdirSync(root+'/fonts',{recursive:true});for(const file of ['PretendardVariable.woff2','OFL.txt'])copyFileSync('public/fonts/'+file,root+'/fonts/'+file);
writeFileSync(root+'/manifest.json',JSON.stringify(manifest,null,2)+'\n');
const cards=manifest.screens.map(s=>`<article><a href="${s.file}" target="_blank"><img src="${s.file}" alt="${s.label}" loading="lazy"/></a><div><h2>${s.label}</h2><p>${s.description}</p><small>${s.width} × ${s.height} PNG</small><a class="download" href="${s.file}" download>이미지 저장</a></div></article>`).join('');
writeFileSync(root+'/gallery.html',`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>표류도 · 완성 UI 이미지</title><style>@font-face{font-family:Pretendard;src:url('fonts/PretendardVariable.woff2') format('woff2');font-weight:45 920}*{box-sizing:border-box}body{margin:0;background:#eceee3;color:#344d3e;font-family:Pretendard,system-ui,sans-serif}header{padding:40px 5vw;background:#314b3d;color:#ececdb}header h1{font-size:30px;margin:8px 0}header p{color:#bdc9ad;line-height:1.8;font-size:13px}header small{letter-spacing:.2em;color:#d4bc80}main{padding:32px 5vw;display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:26px}article{background:#f9f6ed;border:1px solid #c8d3bc;border-radius:16px;overflow:hidden}article>a{display:block;background:#d6ddcb;height:440px;overflow:auto;text-align:center;padding:12px}img{width:100%;max-width:340px;height:auto;display:block;margin:auto}article>div{padding:16px}h2{font-size:16px;margin:0 0 10px}p{font-size:12px;color:#7c8b6d;line-height:1.8;margin:0 0 10px}small{font-size:10px;color:#a08b55}.download{display:block;margin-top:16px;font-size:12px;color:#4e6e44}footer{padding:20px 5vw;font-size:12px;color:#7e8e72}a{color:inherit}</style><header><small>PYO-RYU ISLAND · UI DESIGN</small><h1>표류도 · 기억의 해안</h1><p>프리텐다드를 적용한 완성 UI 이미지 ${manifest.screens.length}장.<br>실제 실행 화면을 캡처했습니다. 퍼즐 정답이 포함된 제작용 자료입니다.</p></header><main>${cards}</main><footer>원본 아트는 art/production/v01 · 실행 및 화면 검토는 프로젝트의 ui-preview.html</footer></html>`);
writeFileSync(root+'/README.md','# 표류도 완성 UI 이미지 v02\n\n전반적인 글꼴을 Pretendard Variable 1.3.9로 통일했다. React 실행 화면을 실제 렌더링해 캡처한 이미지이며 PNG 안의 한국어도 같은 글꼴로 표시된다. 기존 v01은 이전 글꼴의 작업 기록이다. 현재 기준은 이 v02 폴더다.\n\n[이미지 전체 보기](gallery.html) · [화면 메타데이터](manifest.json) · [폰트 라이선스](fonts/OFL.txt)\n\n19개 화면은 360×780 CSS px의 3배 밀도로 저장한 1080×2340 PNG다. 2개는 사용자가 요청한 기존 390×844 구도 재제작이다. 5개는 스크롤 영역 전체를 펼친 긴 PNG로, 내용 누락 없이 화면 구성을 확인할 수 있다.\n\n| 화면 | 이미지 | 픽셀 크기 |\n| --- | --- | --- |\n'+manifest.screens.map(s=>`| ${s.label} | [PNG](${s.file}) | ${s.width}×${s.height} |`).join('\n')+'\n\n폰트 출처: [공식 Pretendard 프로젝트](https://github.com/orioncactus/pretendard). 공식 배포 패키지 1.3.9의 WOFF2와 SIL OFL 라이선스를 함께 보관했다.\n');
console.log('FINAL UI IMAGES',manifest.screens.length);
