import { chromium } from './browser.mjs';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
mkdirSync('test-results',{recursive:true});
const errors=[],failed=[];const b=await chromium.launch({headless:true});
let p;const steps=[];
try{
 p=await b.newPage({viewport:{width:360,height:780}});p.setDefaultTimeout(5000);
 p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.status()+' '+r.url());});
 const button=name=>p.getByRole('button',{name,exact:true});
 const dialog=()=>p.getByRole('dialog');
 const close=()=>dialog().getByRole('button',{name:'닫기',exact:true}).click();
 const investigate=async name=>{await p.locator('.hotspot[aria-label="'+name+'"]').click();};
 const dialogue=async()=>{while(await button('다음 대사').count())await button('다음 대사').click();};
 const count=async n=>{await p.waitForFunction(x=>document.querySelector('.objective>small')?.textContent===x+'%',n*4);steps.push(n);console.log('STAGE',n);};
 const code=async digits=>{await dialog().getByRole('button',{name:'지우기',exact:true}).click();for(const d of digits)await dialog().getByRole('button',{name:d,exact:true}).click();await dialog().getByRole('button',{name:'잠금 해제',exact:true}).click();};
 const bag=async item=>{await p.getByRole('button',{name:/보관함$/}).click();await p.locator('.item-slot').filter({hasText:item}).click();};
 const combine=async(a,c)=>{await bag(a);await dialog().getByRole('button',{name:'조합',exact:true}).click();await p.locator('.item-slot').filter({hasText:c}).click();await dialog().getByRole('button',{name:'조합 확인',exact:true}).click();};
 const map=async name=>{await button('지도').click();await p.locator('.map-room').filter({hasText:name}).click();};
 const reload=async()=>{await p.waitForFunction(()=>document.querySelector('.save-status')?.textContent==='자동 저장됨');await p.reload();await p.getByRole('button',{name:/^이어서 탐색/}).waitFor({state:'visible'});await p.getByRole('button',{name:/^이어서 탐색/}).click();};
 await p.goto('http://127.0.0.1:5173/');await button('새로운 기억').click();await dialogue();
 await investigate('손목의 결박');await close();await count(1);
 await investigate('의자 버팀대');for(let i=0;i<3;i++)await p.getByRole('button',{name:/왼쪽으로 체중 싣기/}).click();await count(2);
 await bag('금속 조각');await dialog().getByRole('button',{name:'사용',exact:true}).click();await investigate('손목의 결박');await dialogue();await count(3);await reload();await count(3);
 await button('선반과 잠금함').click();await investigate('선반의 쪽지');await count(4);
 await investigate('잠금함');await code('714');await dialog().getByRole('status').waitFor();await count(4);await code('417');await count(5);
 await investigate('잠금함 안쪽');await count(6);
 await combine('끈','쪽지 A');assert.match(await dialog().getByRole('status').innerText(),/연결할 방법/);assert.equal(await p.locator('.item-slot').count(),4);
 await close();await button('환기구와 관리실 문').click();await investigate('환기구 덮개');await p.getByRole('button',{name:'드라이버로 나사 풀기'}).click();await count(7);
 await combine('끈','자석');await count(8);await close();await investigate('환기구 안쪽');await p.getByRole('button',{name:'자석 줄로 열쇠 건지기'}).click();await count(9);
 await investigate('관리실 문');await p.getByRole('button',{name:'관리실 열쇠로 문 열기'}).click();await dialogue();await count(10);await reload();await count(10);
 await investigate('찢긴 회로도');await p.getByRole('button',{name:'회로도 이어 붙이기'}).click();await dialog().getByRole('status').waitFor();await count(10);await p.getByRole('button',{name:'두 조각의 위치 바꾸기'}).click();await p.getByRole('button',{name:'회로도 이어 붙이기'}).click();await dialogue();await count(11);
 await investigate('책상 서랍');await count(12);await map('폐창고 감금실');await button('배전함',).first().click();
 await investigate('배전함 덮개');await p.getByRole('button',{name:'드라이버로 배전함 열기'}).click();await count(13);
 await p.getByRole('button',{name:'F1에 퓨즈 넣기'}).click();await dialog().getByRole('status').waitFor();await count(13);await p.getByRole('button',{name:'F2에 퓨즈 넣기'}).click();await count(14);
 await p.getByRole('button',{name:/주차단기 ON으로 전환/}).click();await dialogue();await count(15);await reload();await count(15);
 await map('관리실');await button('점검함과 근무표').click();await investigate('점검 달력');await p.getByRole('button',{name:'점검함으로 돌아가기'}).click();await code('123');await count(16);
 await button('설비실 입구').click();await investigate('설비실 문');await p.getByRole('button',{name:'설비실 문 열고 들어가기'}).click();await count(17);
 await investigate('작업대 전지');await count(18);await combine('전지 없는 UV 램프','배터리 팩');await count(19);await close();
 await button('밸브와 집수정').click();await investigate('배수 작업 표찰');await close();await count(20);
 await investigate('배수 밸브');await p.getByRole('button',{name:'배수 구동'}).click();await dialog().getByRole('status').waitFor();await count(20);
 for(const name of ['바다 유입','저수 연결','배출'])await p.locator('.valve-toggle').filter({hasText:name}).click();await p.getByRole('button',{name:'배수 구동'}).click();await count(21);await reload();await count(21);
 await investigate('집수정 바닥');await count(22);await bag('황동 명판');await p.getByRole('button',{name:'명판 확대 조사'}).click();await p.getByRole('button',{name:'UV 램프로 비추기'}).click();await close();await dialogue();await count(23);
 await button('낮은 통로').click();await investigate('낮은 통로');await investigate('게이트 키패드');await code('2641');await count(24);await reload();await count(24);
 await investigate('외부 게이트');await p.getByRole('button',{name:'밖으로 나간다'}).click();await dialogue();await count(25);assert.equal(await p.locator('.chapter-complete').count(),1);
 await p.screenshot({path:'test-results/ch01-complete.png'});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 const report={status:'passed',viewport:'360x780',steps:[...new Set(steps)],checks:['wrong code','wrong combination retains ingredients','wrong paper order','wrong fuse retains fuse','wrong valves retain handle','reload at P03/P10/P15/P21/P24','complete 25 stages'],pageErrors:errors,failedResponses:failed};
 writeFileSync('test-results/playthrough.json',JSON.stringify(report,null,2));console.log('PLAYTHROUGH OK');
}catch(e){if(p)await p.screenshot({path:'test-results/playthrough-failure.png'});throw e;}finally{await b.close();}

